I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Day7.rpy", line 73, in script
    
Exception: Sayer 'braxon' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Day7.rpy", line 73, in script
    
  File "C:\Users\David\Documents\Ren'py\renpy-6.99.12.4-sdk\renpy\ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\David\Documents\Ren'py\renpy-6.99.12.4-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'braxon' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
STLResistJam 1.0
